### ISSUE TITLE
error parsing admonition blocks

### ISSUE THREAD

**Issue by qjebbs** [docarys/markdown-it-admonition#4]
Thanks for your plugin. 

Please consider following markdown code:

```markdown
source code:

    !!! note
    admonition body
    !!!

render result:

!!! note
admonition body
!!!
```

result:

![image](https://user-images.githubusercontent.com/16953333/41266771-0b891294-6e2b-11e8-84cf-7768e121bc7d.png)

(screenshot from vscode with [markdown extended](https://marketplace.visualstudio.com/items?itemName=jebbs.markdown-extended))

expected result: 

![image](https://user-images.githubusercontent.com/16953333/41267057-7d231386-6e2c-11e8-9c60-9064e5b3d217.png)

(the first part should be a `pre` and second a `admonition`.)

**Comment by sesispla** [comment]
Thanks for the feedback @qjebbs 

Could you please provide the expected HTML? This can help to create unit tests and fix the issue.

**Comment by qjebbs** [comment]
It should be something like this:

```html
<p data-line="0" class="code-line">source code:</p>
<pre data-line="2" class="code-line"><code>!!! note
admonition body
!!!
</code></pre>
<p data-line="6" class="code-line">render result:</p>
<div class="admonition note">
    <p class="admonition-title">Note</p>
    <p data-line="9" class="code-line">admonition body</p>
</div>
```

I've wrote a new implement to fix this, but with different syntax. 
https://github.com/qjebbs/vscode-markdown-extended/blob/master/src/plugin/markdownItAdmonition.ts

**Comment by sesispla** [comment]
Closing this in favour of #7
